# Generated by Django 5.0.6 on 2024-07-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_answercomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answercomment',
            options={'ordering': ('-modified', '-created')},
        ),
    ]
