# Generated by Django 5.0.6 on 2024-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_answercomment_is_reply_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ('-modified', '-created'), 'verbose_name_plural': 'replies'},
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_replies', to='home.commentreply'),
        ),
    ]
