# Generated by Django 5.0.6 on 2024-07-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_answer_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='owner',
        ),
    ]
