# Generated by Django 5.0.6 on 2024-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_user_dislike_owner_rename_user_like_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='questions', to='home.tag'),
        ),
    ]
