# Generated by Django 5.0.6 on 2024-07-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_question_tag_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
